import os
import cv2
import numpy as np

def sortSecond(val):
    return int(val[:-4])

if __name__ == '__main__':
    names = ["Aatrox",
             "Ahri",
             "Akali",
             "Alistar",
             "Amumu",
             "Anivia",
             "Annie",
             "Aphelios",
             "Ashe",
             "Aurelion Sol",
             "Azir",
             "Bard",
             "Blitzcrank",
             "Brand",
             "Braum",
             "Caitlyn",
             "Camille",
             "Cassiopeia",
             "Cho'Gath",
             "Corki",
             "Darius",
             "Diana",
             "Dr. Mundo",
             "Draven",
             "Ekko",
             "Elise",
             "Evelynn",
             "Ezreal",
             "Fiddlesticks",
             "Fiora",
             "Fizz",
             "Galio",
             "Gangplank",
             "Garen",
             "Gnar",
             "Gragas",
             "Graves",
             "Hecarim",
             "Heimerdinger",
             "Illaoi",
             "Irelia",
             "Ivern",
             "Janna",
             "Jarvan IV",
             "Jax",
             "Jayce",
             "Jhin",
             "Jinx",
             "Kai'Sa",
             "Kalista",
             "Karma",
             "Karthus",
             "Kassadin",
             "Katarina",
             "Kayle",
             "Kayn",
             "Kennen",
             "Kha'Zix",
             "Kindred",
             "Kled",
             "Kog'Maw",
             "LeBlanc",
             "Lee Sin",
             "Leona",
             "Lissandra",
             "Lucian",
             "Lulu",
             "Lux",
             "Malphite",
             "Malzahar",
             "Maokai",
             "Master Yi",
             "Miss Fortune",
             "Mordekaiser",
             "Morgana",
             "Nami",
             "Nasus",
             "Nautilus",
             "Neeko",
             "Nidalee",
             "Nocturne",
             "Nunu & Willump",
             "Olaf",
             "Orianna",
             "Ornn",
             "Pantheon",
             "Poppy",
             "Pyke",
             "Qiyana",
             "Quinn",
             "Rakan",
             "Rammus",
             "Rek'Sai",
             "Renekton",
             "Rengar",
             "Riven",
             "Rumble",
             "Ryze",
             "Sejuani",
             "Senna",
             "Sett",
             "Shaco",
             "Shen",
             "Shyvana",
             "Singed",
             "Sion",
             "Sivir",
             "Skarner",
             "Sona",
             "Soraka",
             "Swain",
             "Sylas",
             "Syndra",
             "Tahm Kench",
             "Taliyah",
             "Talon",
             "Taric",
             "Teemo",
             "Thresh",
             "Tristana",
             "Trundle",
             "Tryndamere",
             "Twisted Fate",
             "Twitch",
             "Udyr",
             "Urgot",
             "Varus",
             "Vayne",
             "Veigar",
             "Vel'Koz",
             "Vi",
             "Viktor",
             "Vladimir",
             "Volibear",
             "Warwick",
             "Wukong",
             "Xayah",
             "Xerath",
             "Xin Zhao",
             "Yasuo",
             "Yorick",
             "Yuumi",
             "Zac",
             "Zed",
             "Ziggs",
             "Zilean",
             "Zoe",
             "Zyra"]
    root_path = "D:\\2gray"
    ss = os.listdir(root_path)
    ss.sort(key=sortSecond)

    for name, img_path in zip(names, ss):
        os.mkdir(root_path + "\\" + name)
        img = cv2.imread(root_path + "\\" + img_path)
        img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        for index in range(1, 41):
            cv2.imwrite(root_path + "\\" + name + "\\gray_" + str(index) + ".png", img_gray)
